version: '3'

services:
    metrics:
        image: ${JITSI_CUSTOM_REPO_PREFIX:-jitsi/}metrics:latest
        restart: always
        environment:
            - SCHOOL_ID
        depends_on: 
            - jvb
        networks:
            meet.jitsi:

